### ISSUE TITLE
Error changing mysql port

### ISSUE THREAD

**Issue by v1nc** [paulpierre/informer#3]
I set the mysql port to 3306, but I still get this error:

`raise errors.InterfaceError(
sqlalchemy.exc.InterfaceError: (mysql.connector.errors.InterfaceError) 2003: Can't connect to MySQL server on '127.0.0.1:3320' (111 Connection refused)`

**Comment by paulpierre** [comment]
Hi v1nc which script are you running? You must set this in both bot.py and the mysql connector string at the bottom of build_database.py
