### ISSUE TITLE
maybe something wrong

### ISSUE THREAD

**Issue by b1ngda0** [paulpierre/informer#5]
![1](https://user-images.githubusercontent.com/46914280/71577703-2ce74500-2b30-11ea-922f-50ddefcceb82.png)
![2](https://user-images.githubusercontent.com/46914280/71577710-340e5300-2b30-11ea-8bc6-ce0c73677021.jpg)
after i debugged some bugs, the porgramme likes run normal. but not to continue, can u tell me why? What's wrong? Did not see auto join channels and filter.

**Comment by paulpierre** [comment]
Just curious, what bugs did you find?

It should auto join channels, do you have the list of channels setup in the database? Can you share with me what the state of the database looks like?

**Comment by b1ngda0** [comment]
![1](https://user-images.githubusercontent.com/46914280/71649082-b6706000-2d46-11ea-8d28-9e5776584c0d.jpg)
![2](https://user-images.githubusercontent.com/46914280/71649087-bb351400-2d46-11ea-8125-ff7117c9303f.jpg)
![3](https://user-images.githubusercontent.com/46914280/71649094-c1c38b80-2d46-11ea-8a47-4f851d531a11.jpg)
![4](https://user-images.githubusercontent.com/46914280/71649098-c4be7c00-2d46-11ea-8e23-ab0ffcb01bd5.jpg)
All is normal.

**Comment by b1ngda0** [comment]
i tried ur channel list, and i run the bot.py also just connection complete, there's no other reaction.
