### ISSUE TITLE
 ERROR: unsatisfiable constraints:    python (missing):      required by: world[python]

### ISSUE THREAD

**Issue by VixusFoxy** [paulpierre/informer#8]
Was trying to follow the steps and happened into an error at the docker build step;
```

 ERROR: unsatisfiable constraints:
   python (missing):
     required by: world[python]
     
```
     
I fixed it by changing the dockerfile to reference "python3" specifically. :)

**Comment by paulpierre** [comment]
Got it! Thank you!
